const COUNTRY_MAP: Record<string, string> = {
  "United States": "Estados Unidos",
  "Japan": "Japón",
  "United Kingdom": "Reino Unido",
  "Canada": "Canadá",
  "France": "Francia",
  "Germany": "Alemania",
  "Switzerland": "Suiza",
  "Australia": "Australia",
  "Netherlands": "Países Bajos",
  "China": "China",
  "South Korea": "Corea del Sur",
  "Korea": "Corea del Sur",
  "Sweden": "Suecia",
  "Denmark": "Dinamarca",
  "Hong Kong": "Hong Kong",
  "Spain": "España",
  "Italy": "Italia",
  "Brazil": "Brasil",
  "India": "India",
  "Taiwan": "Taiwán",
  "Singapore": "Singapur",
  "Norway": "Noruega",
  "Finland": "Finlandia",
  "Belgium": "Bélgica",
  "Austria": "Austria",
  "Ireland": "Irlanda",
  "Portugal": "Portugal",
  "Mexico": "México",
  "Russia": "Rusia",
  "Poland": "Polonia",
  "Turkey": "Turquía",
  "South Africa": "Sudáfrica",
  "Israel": "Israel",
  "New Zealand": "Nueva Zelanda",
  "Greece": "Grecia",
  "Czech Republic": "República Checa",
  "Hungary": "Hungría",
  "Indonesia": "Indonesia",
  "Malaysia": "Malasia",
  "Thailand": "Tailandia",
  "Philippines": "Filipinas",
  "Chile": "Chile",
  "Colombia": "Colombia",
  "Peru": "Perú",
  "Argentina": "Argentina",
  "Egypt": "Egipto",
  "Saudi Arabia": "Arabia Saudí",
  "United Arab Emirates": "Emiratos Árabes",
  "Qatar": "Catar",
  "Kuwait": "Kuwait",
  "Pakistan": "Pakistán",
  "Other": "Otros",
  "Emerging Markets": "Mercados emergentes",
  "Developed Markets": "Mercados desarrollados",
  "Europe": "Europa",
  "Asia Pacific": "Asia Pacífico",
  "Asia": "Asia",
  "North America": "Norteamérica",
  "Latin America": "Latinoamérica",
  "Middle East": "Oriente Medio",
  "Africa": "África",
  "Global": "Global",
  "Eurozone": "Eurozona",
};

const SECTOR_MAP: Record<string, string> = {
  "Information Technology": "Tecnología",
  "Technology": "Tecnología",
  "Financials": "Finanzas",
  "Finance": "Finanzas",
  "Health Care": "Salud",
  "Healthcare": "Salud",
  "Health care": "Salud",
  "Consumer Discretionary": "Consumo discrecional",
  "Consumer Staples": "Consumo básico",
  "Industrials": "Industria",
  "Industrial": "Industria",
  "Communication Services": "Comunicaciones",
  "Communications": "Comunicaciones",
  "Energy": "Energía",
  "Materials": "Materiales",
  "Real Estate": "Inmobiliario",
  "Utilities": "Servicios básicos",
  "Basic Materials": "Materiales básicos",
  "Consumer Goods": "Bienes de consumo",
  "Consumer Services": "Servicios al consumidor",
  "Other": "Otros",
  "Cryptocurrency": "Criptomonedas",
  "DeFi": "DeFi",
};

export const translateCountry = (name: string): string => COUNTRY_MAP[name] ?? name;

export const translateSector = (name: string): string => SECTOR_MAP[name] ?? name;

/**
 * Convierte un número a string en formato español para inputs (sin separador de miles).
 * Ej: 291.403 → "291,403" | 3702.64 → "3702,64"
 */
export const numToInputStr = (n: number | null | undefined, maxDecimals = 6): string => {
  if (n == null || !Number.isFinite(n as number)) return "";
  return (n as number).toLocaleString("es-ES", {
    maximumFractionDigits: maxDecimals,
    useGrouping: false,
  });
};
