/**
 * One-off generator: converts world-atlas's TopoJSON world map into a flat
 * { [ISO2]: svgPathD } lookup, precomputed at build time so the app never
 * ships d3-geo/topojson-client or does map projection math at runtime.
 *
 * Run with: npx ts-node --compiler-options '{"module":"commonjs"}' scripts/generate-world-map-paths.ts
 * Output: src/assets/worldMapPaths.ts
 */
import * as fs from "fs";
import * as path from "path";
import { geoPath, geoNaturalEarth1 } from "d3-geo";
import { feature } from "topojson-client";
import worldCountries from "world-countries";
// @ts-ignore - no type declarations shipped for the JSON data files themselves
import topology from "world-atlas/countries-50m.json";

const VIEWBOX_WIDTH = 960;
const VIEWBOX_HEIGHT = 500;

const numericToIso2 = new Map<string, string>();
for (const c of worldCountries as any[]) {
  if (c.ccn3) numericToIso2.set(c.ccn3, c.cca2);
}

const fc: any = feature(topology as any, (topology as any).objects.countries);

const projection = geoNaturalEarth1().fitSize([VIEWBOX_WIDTH, VIEWBOX_HEIGHT], fc);
// Full float precision is pointless here — the map renders at a few hundred
// px wide in the app, and untruncated coordinates were bloating the
// generated file to ~1.4MB. One decimal digit is visually indistinguishable
// at this display size and cuts the file drastically.
const pathGenerator = geoPath(projection).digits(1);

const paths: Record<string, string> = {};
let matched = 0;
let unmatched: string[] = [];

for (const f of fc.features) {
  const iso2 = numericToIso2.get(String(f.id));
  const d = pathGenerator(f);
  if (!d) continue;
  if (!iso2) {
    unmatched.push(`${f.id} (${f.properties?.name ?? "?"})`);
    continue;
  }
  // A couple of numeric codes map to the same ISO2 in edge cases (disputed
  // territories); keep the first (largest, since world-atlas lists the
  // main landmass first for those cases) rather than overwrite it.
  if (!paths[iso2]) paths[iso2] = d;
  matched++;
}

console.log(`Matched ${matched}/${fc.features.length} country shapes to an ISO2 code.`);
if (unmatched.length) {
  console.log(`Unmatched (no ISO2 in world-countries, skipped): ${unmatched.join(", ")}`);
}

const outPath = path.join(__dirname, "..", "src", "assets", "worldMapPaths.ts");
const header = `// AUTO-GENERATED by scripts/generate-world-map-paths.ts — do not edit by hand.\n// Regenerate with: npx ts-node --compiler-options '{"module":"commonjs"}' scripts/generate-world-map-paths.ts\n\n`;
const body =
  `export const WORLD_MAP_VIEWBOX = "0 0 ${VIEWBOX_WIDTH} ${VIEWBOX_HEIGHT}";\n\n` +
  `export const WORLD_MAP_PATHS: Record<string, string> = ${JSON.stringify(paths, null, 0)};\n`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, header + body);
console.log(`Wrote ${outPath} (${Object.keys(paths).length} countries, ${(body.length / 1024).toFixed(0)} KB)`);
